### ISSUE TITLE
Ability to create a lambda(or something) of methods that will be have N of those methods called

### ISSUE THREAD

**Issue by StephenOTT** [nomemory/mockneat#46]
Any thoughts on the ability to have some sort of listing of methods or a lambda/builder that allows you to define a probability that the method will be called, and be able to set a Min and/or max methods to be called.

Such as: I have 4 snippets of code: I want each snippet have a probability of 50%, and I want that a minimum of 1 method will always be called, but which will be random).

**Comment by nomemory** [comment]
I think a feature like this will be a little bit to specific to implement in the library itself, but it can be easily done with some additional code, something like this maybe:

```
import static net.andreinc.mockneat.unit.objects.From.from;
import static net.andreinc.mockneat.unit.types.Ints.ints;

public class MethodsExample {

    @FunctionalInterface
    public interface Snippet {
        void call();
    }

    public static void chooseAtLeastOneAndDo(Snippet... snippets) {
        from(snippets)
                .set(ints().range(1, snippets.length))
                .get()
                .forEach(Snippet::call);
    }

    public static void main(String[] args) {
        chooseAtLeastOneAndDo(
                () -> System.out.println("Some snippet 1"),
                () -> System.out.println("Some snippet 2"),
                () -> System.out.println("Some snippet 3"),
                () -> System.out.println("Some snippet 4"),
                () -> System.out.println("Some snippet 5")
        );
    }
}
```
Depending on what you want your code can become more complex, but this should be a starting point.

PS: I've created my own `@FunctionalInterface` for a `void()` method for more clarity (I dislike using `Runnable` because people might assume it's something thread related).

**Comment by StephenOTT** [comment]
Great points.  Will review further and report back. Thanks!
